#cloud-config

hostname: devbox

ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key

users:
  - name: vagrant
    passwd: $6$rounds=4096$e/1eVLBLIyx4$rugS.gza5WFsEwxc9RQLa9mL0owrjJNpjG3bfYWBNTT55B8mPFagke.HX4YkS3oQSmD8/AyrcSD8XQMFcSf2P/
    groups:
      - sudo
      - docker
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key

coreos:
  etcd:
    name: devbox
  units:
    - name: etcd.service
      command: start
    - name: fleet.service
      command: start
    - name: proxy.service
      command: start
      content: |
        [Unit]
        Description=Run proxy
        After=docker.service
        Requires=docker.service

        [Service]
        User=core
        Restart=always
        RestartSec=10s
        ExecStartPre=/usr/bin/docker pull dockito/proxy:latest
        ExecStartPre=/usr/bin/docker ps -a -q | xargs docker rm
        ExecStart=/usr/bin/docker run --privileged=true -rm -name proxy -v /var/run/docker.sock:/tmp/docker.sock -p 80:80 dockito/proxy:latest
        ExecStartPost=/usr/bin/docker ps -a -q | xargs docker rm
        ExecStop=/usr/bin/docker kill proxy
        ExecStopPost=/usr/bin/docker ps -a -q | xargs docker rm

        [Install]
        WantedBy=local.target
