# -*- mode: ruby -*-
# # vi: set ft=ruby :


unless Vagrant.has_plugin?("rancheros-guest")
  raise 'rancheros-guest is not installed! run: vagrant plugin install rancheros-guest'
end

Vagrant.configure("2") do |config|
  VM_MEMORY = "1512"
  VM_IP = "10.10.10.10"

  config.ssh.username = "rancher"

  config.vm.network :private_network, ip: VM_IP, netmask: "255.255.255.0"

  # Disable the base shared folder, guest additions are unavailable.
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider :virtualbox do |vb|
    # Guest Additions are unavailable.
    vb.check_guest_additions = false
    vb.functional_vboxsf = false

    # Fix docker not being able to resolve private registry in VirtualBox
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]

    vb.customize ["modifyvm", :id, "--memory", VM_MEMORY]
  end

  config.vm.provider :vmware_fusion do |vf|
    vf.functional_hgfs = false
    vf.vmx["memsize"] = VM_MEMORY
    vf.vmx["numvcpus"] = "2"
  end
end
